module.exports = {
  GREETING: "GREETING",

  JOIN_MAGICPIN: "JOIN_MAGICPIN",

  ASK_BENEFITS: "ASK_BENEFITS",

  ASK_PRICING: "ASK_PRICING",

  ASK_COMMISSION: "ASK_COMMISSION",

  ASK_OFFERS: "ASK_OFFERS",

  ASK_VERIFICATION: "ASK_VERIFICATION",

  ASK_SUPPORT: "ASK_SUPPORT",

  PROVIDE_DETAILS: "PROVIDE_DETAILS",

  THANKS: "THANKS",

  GOODBYE: "GOODBYE",

  HOSTILE: "HOSTILE",

  GENERAL: "GENERAL"
};